### ISSUE TITLE
Entity disambiguation threshold and normalization 

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-stanbol#1]
When receiving entities from the WordLift/Stanbol end-point there should be a threshold to filter out any entity that has a confidence score < 0.25; this also requires the engine to perform a normalisation of the confidence score for each text annotation.  

Let's have a look at this example: 

entity disambiguation for "Nicky Hayden" - here follows the results currently provided:

http://dbpedia.org/resource/Phillip_Island_Grand_Prix_Circuit ( 22.863733 )
http://dbpedia.org/resource/Arai_Helmet ( 23.922375 )
http://dbpedia.org/resource/AMA_Superbike_Championship ( 19.106102 )
http://dbpedia.org/resource/69_(number) ( 21.521303 )
http://dbpedia.org/resource/Nicky_Hayden ( 481.80249 )  

It is clear that if we normalise the score in a range between 0 and 1 we could easily filter out anything but the last one that represents the most appropriate result.  

In order to do so the best approach is to develop a new engine that given all the results of the chain is capable of normalising the score values and add a threshold; this could be use regardless of the chain configuration.

**Comment by ziodave** [comment]
It has been implemented in the FreeBase engine.
